.PHONY: clean All

All:
	@echo "----------Building project:[ SelfCheck - Debug ]----------"
	@cd "SelfCheck" && "$(MAKE)" -f  "SelfCheck.mk"
clean:
	@echo "----------Cleaning project:[ SelfCheck - Debug ]----------"
	@cd "SelfCheck" && "$(MAKE)" -f  "SelfCheck.mk" clean
