.PHONY: clean All

All:
	@echo "----------Building project:[ Chapter2-6 - Debug ]----------"
	@cd "Chapter2-6" && "$(MAKE)" -f  "Chapter2-6.mk"
clean:
	@echo "----------Cleaning project:[ Chapter2-6 - Debug ]----------"
	@cd "Chapter2-6" && "$(MAKE)" -f  "Chapter2-6.mk" clean
