.PHONY: clean All

All:
	@echo "----------Building project:[ CopyConstruct - Debug ]----------"
	@cd "CopyConstruct" && "$(MAKE)" -f  "CopyConstruct.mk"
clean:
	@echo "----------Cleaning project:[ CopyConstruct - Debug ]----------"
	@cd "CopyConstruct" && "$(MAKE)" -f  "CopyConstruct.mk" clean
