.PHONY: clean All

All:
	@echo "----------Building project:[ SectionChallenge2Ans - Debug ]----------"
	@cd "SectionChallenge2Ans" && "$(MAKE)" -f  "SectionChallenge2Ans.mk"
clean:
	@echo "----------Cleaning project:[ SectionChallenge2Ans - Debug ]----------"
	@cd "SectionChallenge2Ans" && "$(MAKE)" -f  "SectionChallenge2Ans.mk" clean
