.PHONY: clean All

All:
	@echo "----------Building project:[ LettertoNumbers - Debug ]----------"
	@cd "LettertoNumbers" && "$(MAKE)" -f  "LettertoNumbers.mk"
clean:
	@echo "----------Cleaning project:[ LettertoNumbers - Debug ]----------"
	@cd "LettertoNumbers" && "$(MAKE)" -f  "LettertoNumbers.mk" clean
