.PHONY: clean All

All:
	@echo "----------Building project:[ SectionChallence - Debug ]----------"
	@cd "SectionChallence" && "$(MAKE)" -f  "SectionChallence.mk"
clean:
	@echo "----------Cleaning project:[ SectionChallence - Debug ]----------"
	@cd "SectionChallence" && "$(MAKE)" -f  "SectionChallence.mk" clean
