.PHONY: clean All

All:
	@echo "----------Building project:[ ReviewExercises - Debug ]----------"
	@cd "ReviewExercises" && "$(MAKE)" -f  "ReviewExercises.mk"
clean:
	@echo "----------Cleaning project:[ ReviewExercises - Debug ]----------"
	@cd "ReviewExercises" && "$(MAKE)" -f  "ReviewExercises.mk" clean
