.PHONY: clean All

All:
	@echo "----------Building project:[ stringFunctions - Debug ]----------"
	@cd "stringFunctions" && "$(MAKE)" -f  "stringFunctions.mk"
clean:
	@echo "----------Cleaning project:[ stringFunctions - Debug ]----------"
	@cd "stringFunctions" && "$(MAKE)" -f  "stringFunctions.mk" clean
