.PHONY: clean All

All:
	@echo "----------Building project:[ LABBool - Debug ]----------"
	@cd "LABBool" && "$(MAKE)" -f  "LABBool.mk"
clean:
	@echo "----------Cleaning project:[ LABBool - Debug ]----------"
	@cd "LABBool" && "$(MAKE)" -f  "LABBool.mk" clean
