.PHONY: clean All

All:
	@echo "----------Building project:[ ReviewExercise - Debug ]----------"
	@cd "ReviewExercise" && "$(MAKE)" -f  "ReviewExercise.mk"
clean:
	@echo "----------Cleaning project:[ ReviewExercise - Debug ]----------"
	@cd "ReviewExercise" && "$(MAKE)" -f  "ReviewExercise.mk" clean
