.PHONY: clean All

All:
	@echo "----------Building project:[ Project7 - Debug ]----------"
	@cd "Project7" && "$(MAKE)" -f  "Project7.mk"
clean:
	@echo "----------Cleaning project:[ Project7 - Debug ]----------"
	@cd "Project7" && "$(MAKE)" -f  "Project7.mk" clean
