.PHONY: clean All

All:
	@echo "----------Building project:[ CalculFiles1 - Debug ]----------"
	@cd "CalculFiles1" && "$(MAKE)" -f  "CalculFiles1.mk"
clean:
	@echo "----------Cleaning project:[ CalculFiles1 - Debug ]----------"
	@cd "CalculFiles1" && "$(MAKE)" -f  "CalculFiles1.mk" clean
